name: SKY UX CI

on:
  pull_request:
    branches:
      - master
      - 3.x.x
  push:
    branches:
      - master
      - 3.x.x
    tags:
      - '*.*.*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: blackbaud/skyux-sdk-actions@after-library-build-script
        with:
          browser-stack-access-key: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
          browser-stack-username: ${{ secrets.BROWSER_STACK_USERNAME }}
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          npm-token: ${{ secrets.NPM_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          after-build-public-library-success: ./scripts/prepare-package.js
      - uses: codecov/codecov-action@v1
